# Generated by Django 4.2.6 on 2023-10-30 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="timeZone",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 10, 30, 18, 40, 59, 882026, tzinfo=datetime.timezone.utc
                ),
                max_length=5,
            ),
            preserve_default=False,
        ),
    ]
