# Generated by Django 4.2.6 on 2023-10-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lastMissionDeletionDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
