# Generated by Django 4.2.6 on 2024-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="wallet",
            field=models.CharField(default="None", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
