# Generated by Django 4.2.6 on 2024-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_deviceid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lastMissionDeletionDate",
            field=models.DateTimeField(blank=True, max_length=50, null=True),
        ),
    ]
