# Generated by Django 4.2.6 on 2023-12-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
