# Generated by Django 4.2.6 on 2024-02-05 13:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_lastmissiondeletiondate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="deviceId",
        ),
    ]
