# Generated by Django 4.2.6 on 2024-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_remove_user_deviceid"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="isEligibleForReward",
            field=models.BooleanField(default=False),
        ),
    ]
