# Generated by Django 4.2.6 on 2024-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_iseligibleforreward"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="deletionTimezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
