# Generated by Django 4.2.6 on 2024-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_deletiontimezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
