# Generated by Django 4.2.6 on 2023-12-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_wallet_address_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="wallet_address",
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
