# Generated by Django 4.2.6 on 2024-01-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="prevDate",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
