# Generated by Django 4.2.6 on 2023-10-30 18:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "missions",
            "0002_rename_name_mission_title_remove_mission_description_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="timeZone",
        ),
    ]
