# Generated by Django 4.2.6 on 2023-11-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0004_alter_mission_prevdate_alter_mission_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
