# Generated by Django 4.2.6 on 2024-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0004_alter_mission_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="prevDate",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="startDate",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
