# Generated by Django 4.2.6 on 2024-02-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("missions", "0008_remove_mission_iscompleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="startTimezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
